package com.tech2java.drools.example2;

import com.tech2java.drools.domain.Passport;

rule "Valid passport"
  dialect "java"
  when
	Passport( !isExpired(), unusedVisaPages > 0 )
  then
	System.out.println("This passport is CORRECT");
end

rule "Expired"
  dialect "java"
  when
	Passport(isExpired())
  then
	System.out.println( "This passport is INVALID because it is expired" );
end

rule "full passport"
  dialect "java"
  when
	Passport(unusedVisaPages == 0 )
  then
	System.out.println( "This passport is INVALID because it has no space for visa" );
end